language: node_js
sudo: false
branches:
  only:
    - master  #只监测master分支
env:
  # - PACKAGE_VERSION="1.0.*"
node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run bootstrap
        # - npm run build
      before_script:
        - echo -e "registry=${registry}\nemail=songlei@aiyongtech.com\nalways-auth=true\n_auth=\"${auth}\"" >> .npmrc;
        - cat .npmrc;
