language: node_js
sudo: false
branches:
  only:
    - master  #只监测master分支
env:
  - PACKAGE_VERSION="1.0.*"
node_js:
  - "10"

deploy:
  provider: npm
  username: ${user}
  password: ${pw}
  organization: myorganization
  space: staging
  app_name: app_name

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm config set @tangram:registry ${registry}
        - echo ${user};
        - npm login --registry=${registry}
        - ${user}
        - ${pw}
        - npm install
        - npm run bootstrap
        # - npm run build
      before_script:
        - echo "1/r/n 2/r/n" >> .npm;
        - cat .npm;
